### PR TITLE
Balance Sheet Implementation - GCI - Hellhound14

### PR DESCRIPTION
**Pull request by hellhound14**
Added a .pdf document by the name "HELLHOUND14" as guide to introduce a balance sheet in Postgresql.

### CODE REVIEW

**Comment by hellhound14** [comment]
Implemented a balance sheet through Postgresql

**Comment by pavanagrawal123** [comment]
Please follow these instructions:
How do I add a item into this gallery?
Check content/feature/example.md to see an example item in the gallery. To add something into this repository, you will need to open a pull request into this repository.

**Comment by hellhound14** [comment]
I'm a little lost what exactly do I need to do now??

**Comment by pavanagrawal123** [comment]
Can you ping me on the PG slack so I can help you out there?

**Comment by hellhound14** [comment]
I'm there as Hellhound14, I have already contacted you.

**Pull request closed without merging**
