### PR TITLE
Pivot Tables Entry

### PR DESCRIPTION
**Pull request by lightspeedana**
I added a new entry into the gallery which focuses on transaction management as a use of SQL.

### CODE REVIEW

**Comment by lightspeedana** [comment]
I altered the entry to focus on Pivot Tables instead.

**Comment by lightspeedana** [comment]
I added a sample input and output to the file.

**Comment by lightspeedana** [comment]
Completed my example and used all sample data - limited the scope of the pivot table for more accessibility.

**Comment by lightspeedana** [comment]
My work should be updated with crosstab now.

**Comment by lightspeedana** [comment]
Added the crosstab function.

**Comment by pavanagrawal123** [comment]
I can't get the example to work right:
image

**Comment by lightspeedana** [comment]
The example should work now.

**Comment by pavanagrawal123** [comment]
@lightspeedana with the lastest changes, the example no longer is a true pivot table, and there's no point for a cross tab, because this is just a group by. I really liked the example before this, and I believe you can get it work!

**Comment by lightspeedana** [comment]
I think I've finished it! Hopefully this should work appropriately - reverted to the old example.

**Comment by pavanagrawal123** [comment]
@lightspeedana With this commit again, the task of pivot tables is not accomplished. This can very easily be done with group by, which defeats the purpose of cross tab.

**Comment by pavanagrawal123** [comment]
@lightspeedana this example still does not work. Can you include some screenshots to what you are running in your terminal? The inner query in the crosstab doesn't seem to work.

**Pull request closed without merging**
